services:
  redmine:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - REDMINE_PLUGINS_MIGRATE:true
      - RAILS_ENV=development
    volumes:
      - ./.volumes/files:/usr/src/redmine/files
      - ./.volumes/sqlite:/usr/src/redmine/sqlite
      - ./:/usr/src/redmine/plugins/redmine_ai_summary
